server:
  port: 9001
  address: localhost

spring:
  application:
    name: DEPARTMENT-SERVICE
#  cloud:
#    config:
#      enabled: true
#      uri: http://localhost:9296

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/department
    username: root
    password: 1998

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost